NOSTORY: VPC Endpoint commit
boldlink/terraform-aws-vpc-endpoint pull request #1
Opened 2022-03-17 10:37 UTC by patrickmukumbu

2022-03-17 10:52 UTC, mariomerco commented
Just added a quick comment that there's a link in the `README.md` that is not loading.

Other than that, looks good!

2022-03-17 10:57 UTC, mariomerco requested changes

2022-03-17 10:57 UTC, mariomerco commented on README.md
> +Example available [here](https://github.com/boldlink/terraform-aws-vpc-endpoint/tree/main/examples)
This link is 404ing

2022-03-17 18:46 UTC, JohnNMwangi approved these changes

2022-03-18 15:54 UTC, mariomerco approved these changes
LGTM! Thanks

2022-03-18 17:28 UTC, merged